name: bms_shopping_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">= 2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  firebase_auth: ^4.0.0 
  firebase_core: ^2.15.0 
  cloud_firestore: ^5.2.0 
  flutter_icons: ^1.1.0
  google_nav_bar: ^5.0.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  sqflite: ^2.0.0+3
  path_provider: ^2.0.11
  carousel_slider: ^4.2.0
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.15
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/locale/
